version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - PORT=3000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - JWT_EXPIRATION_MINUTES=15
      - MONGO_URI=mongodb://womywomwoo:GZyjV0lkn98uiJBNpw%21%2a99mgm9%2amZb%40BS2j%249UnpZekqsmluvO%249%24PWh%26HHCorFuz57srJlxn3q8hse%2afFAAhEMrBjzA5HDb%2a5c@localhost:27017/SarpeTravel?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      - MONGO_URI_TESTS=mongodb://womywomwoo:GZyjV0lkn98uiJBNpw%21%2a99mgm9%2amZb%40BS2j%249UnpZekqsmluvO%249%24PWh%26HHCorFuz57srJlxn3q8hse%2afFAAhEMrBjzA5HDb%2a5c@localhost:27017/SarpeTravel?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      - EMAIL_PORT= 25
      - EMAIL_HOST= lol@gmail.com
      - EMAIL_USERNAME= lolkek
      - EMAIL_PASSWORD= uwu123
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
